### PR TITLE
U value check for imperial inputs

### PR DESCRIPTION
**Pull request by MingboPeng**
add a warning msg for possible imperial U value.

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@MingboPeng thanks! You forgot to create the new userobject and also change the date. I'll assign this to @chriswmackey to review. I have no idea about IP numbers.

**Comment by MingboPeng** [comment]
@mostaphaRoudsari , I just made this mistake, and the result doesn't make sense. I was looking for reason all day yesterday. I check all schedules, load settings, and all constructions but windows (because I created the material, so trusted myself, didn't check it again.). I was stupid. .

**Comment by mostaphaRoudsari** [comment]
@MingboPeng we know that you're not! I think to give a warning about the value range is going to be very useful.

**Comment by devngc** [comment]
@MingboPeng thanks!

**Comment by chriswmackey** [comment]
@MingboPeng ,
This is definitely a useful feature and thank you for it.  I would say the tipping point around where a U-value is certainly in IP is around 0.5.  My office occasionally gets window U-values below 1.0 (SI) by doing a lot of fancy things (warm edge spacers, wooden window frames, triple-pane glass).  Once you are down to 0.5, though, you need something really fancy like aerogel.  If you update the component with this number and include the userobject, I'll merge it in.

**Comment by MingboPeng** [comment]
created a new pull

**Pull request closed without merging**
