### PR TITLE
Updates to IES components

### PR DESCRIPTION
**Pull request by sariths**
Added a few bug fix fixes and a new component. The new features are below:
2-16-2016 1-48-29 pm

2-16-2016 1-44-56 pm

The gh file demonstrating these components is here: https://www.dropbox.com/s/oeap8fij4o4prgq/IES_Electric_Lighting_Grid-based_calculations.gh?dl=0

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@sariths great! Thanks. My only suggestion is to share the example file as a Hydra so they are easy to find for later.

**Comment by daweissman** [comment]
@sariths Found another few issues with importing ies files. See:https://www.dropbox.com/s/mn6y1h3twwucrie/IES_Electric_Lighting_Grid-based_calculations_DW.gh?dl=0. 

Issue 1: Some ies files don't posses correct lumen data, so providing a method to input lumens to overide the file would be necessary) -

Issue 2: Individual units vs continuous lengths
In the case of your sample fixture, a 2x2 troffer, it's a unitized fixture, no scaling needed. However more and more we work with linear fixtures, where the ies file can be scaled linearly over a length, and effectively stretch the photometric based on the lumen output and fixture size.  check out the way you can manipulate ies files in 3ds max for reference: ies-3dsmax  Here, the lumens sometimes comes in correctly from the file, sometimes not, but we can modify if need be. then we use the 'dimming' for light loss factor. in the shape/shadows panel, the size of the area will correspond to how the photometric is arrayed. so if the length is 2', it will compress the lumens into a 2' fixture. if set to 4', the lumens are spread evenly across, so if you put the light up against a wall, you wouldn't see a spike at the center, but an even distribution across the length. let me know if this doesn't make sense and we can discuss further.

**Comment by sariths** [comment]
Hi @daweissman,  thank you for the inputs. In Issue 1, are you referring to the -1 in the lumens value in the IES file?

**Comment by daweissman** [comment]
hey @sariths yea just realized i could manually change that number to put the correct lumens in...

**Comment by daweissman** [comment]
disregard last comment @sariths that doesn't work. this is an LED fixture, which is what the -1 signifies

**Comment by sariths** [comment]
@daweissman Yes. I was going to say that (about the -1). 

I have some old code lying around that calculates lumen output for the luminaire too (based on candela values as per  zonal lumen method). I will incorporate that into the Honeybee module eventually. Then it will be possible to see the lumen output for luminaires with absolute photometry, as a lot of LED luminaires tend to be.

I am not completely clear about the scaling thing that you mentioned. Does it work with AGI too? If not, can you share a simple 3ds Max file where you've done something similar? What happens if the luminaire is say 1 feet and you scale the luminaire to 3.5 feet ?

**Comment by daweissman** [comment]
hey @sariths sounds good on the lumens - yes that was going to be my suggestion as well.

regarding the scaling issue - in AGI you perform the scaling manually in the Advanced Settings under Luminaire Subdivision (see image below). in 3ds max, it's actually the Nvidia iRay render engine that performs the subdivision automatically. i bet it'd be easier to implement the setting manually via an input that can force a subdivision similar to AGI. 
advanced

**Comment by sariths** [comment]
@daweissman This is really interesting,  and also a practice that I have been oblivious to. I haven't done a lighting calculation professionally in almost 5 years. So, I have somewhat naive questions: 

1. Does the lumen output (of the scaled luminaire ) scale too? I mean if you were to scale a 4'x1' luminaire to 8'x1' does the lumen ouput have to increase two-fold too?

2. What would you expect the photometric-web to look like if such a scaling were to be done? For example, if you scale a luminaire to thrice it's length will there be three photometric-webs ?

3. Finally, how is this different from simply creating an array of luminaires ?

I am a 100% confident that such photometric manipulation can be done inside Radiance although I am not sure of the amount work it will take (and if I am up to the task). I can 'see' the solution to this with the Radiosity method that AGI-32 uses. 

If you think this is something that lighting designers are using on a regular basis, I can create a separate issue for this feature and we can collaborate further.

**Comment by daweissman** [comment]
HEY @sariths 

test-spacing

so i think there may be a way around this based on what you're questioning. - say for instance i'm studying a grazing fixture like this Acclaim fixture](http://www.acclaimlighting.com/products/product-detail/product/dynagraze-exterior-ho.html). Here's [the ies file i'm using](https://dl.dropboxusercontent.com/u/4919368/Dyna_Graze_HO_Ext_1__4000K_30_X_60.ies) i space this fixture on 1' increments, since the ies file is for 1' - and it looks pretty correct. The important aspect here is that the fixture body should be visible in the viewport as 1' x ~2" - the problem is that the ies file doesn't in this case call that correctly in the code, only in the notes "[TEST] DYNA GRAZE HO EXTERIOR 1' 4000K 30 X 60 DEG 120V". 

in AGI or 3ds max if i wanted 8' of this fixture, i'd likely scale it to be 4' long since the fixture comes in 1' and 4' increments, then place 2 fixtures. in this scenario, subdividing the fixture is necessary. however, since in grasshopper multiplying the fixture 8 times is no harder than 2x, leaving it 1' long isn't really an issue. also i don't forsee using radiance for beautiful visualizations, so maybe it's a wash, as your questions suggest.

on another note, found another ies type that doesn't seem to work with this build. check out http://ecosenselighting.com/products/

**Comment by sariths** [comment]
@daweissman I patched the issue with filenames and paths with spaces. It will be available once the pull request goes through. The ies files with http://ecosenselighting.com/products/ seem to be working with the patched component. I think the issue was that the folder that the .ies file is extracted to  had spaces in it.

The ies file from Acclaim lighting is actually defined as a point source. I am not sure why the manufacturer decided to construct the photometric report that way. I do, however, now get the idea behind defining custom shapes for IES files. Let me see what can be done on this issue. 

Sarith

**Comment by daweissman** [comment]
This is great @sariths nice work! 

Yea every company does ies files differently - some test their products in house, others have an outside contractor do it; others do the shady thing and post results from photopia instead of from the actual fixture. and we see some companies posting initial lumens from their boards instead of actual lumens from the fixture. upshot, there's a lot of variation and the more flexible the analysis program, the more robust the possibility for accurate analysis and design. 

thanks!
dan

**Comment by sariths** [comment]
Hi @daweissman,I tested the luminaire scaling thing with on Grasshopper. Here are a couple of images:
1. The first image is an array of three luminaires connected end-to-end (like one would do in cove lighting):

3-5-2016 4-11-48 pm

2.The second is the same luminaire scaled to three times its length to mimic the previous array. The candela multiplier is x3 . 
3-5-2016 4-12-47 pm

In the second case the photometry is scaled to reflect the modified dimensions of the luminaire such that candelas are distributed along the new length. Is this what you expect when you scale a luminaire?  If so, it is a very easy think to add to the code.

**Comment by daweissman** [comment]
@sariths i think so! what ies file is this? to see the effect more clearly, try an asymmetric distribution such as this: http://www.acclaimlighting.com/uploads/tx_acclaimlighting/downloads_us/Dyna_Graze_HO_Ext_DMX_RGBW_10x60.ies

**Comment by sariths** [comment]
@daweissman I tried the IES file you suggested. There are 59 luminaires in the simulation. 
 
The images below are from when the luminaire is scaled inside the ies file and Radiance. This approach muddles up the photometric-web calcs but is fairly straight forward.:
3-5-2016 6-04-18 pm
3-5-2016 6-04-34 pm
The other approach is to get the code to read an IES file and then have it arrange the luminaires end-to-end based on input.
3-5-2016 6-07-52 pm
3-5-2016 6-08-08 pm

From a computational perspective, the Radiance settings in both cases are the same. As indicated by the vertical wall scallops in the first case, although Radiance does discretize the luminaire, it doesn't discretize to the extent where it can replicate the image in the second case. The illuminance peaks in both cases are almost the same, however, case 2 seems to be the physically realistic calculation. 

When you scale a luminaire in a simulation (in AGI or 3ds Max), are you trying to replicate an end-to-end array as you see in case 2 ? 

Either of these two approaches can be implemented in Honeybee although doing the first one would most likely add a computational overhead from Radiance as we'd have to crank up the settings in the whole scene and also force further source subdivision.

**Comment by daweissman** [comment]
hey @sariths sorry for the delay here - so it looks like you're getting the same results from both? i'd say go with the less computationally expensive version!

**Comment by sariths** [comment]
@daweissman Thanks for the input. I will be implementing this along with a few other fixes within a couple of weeks.

**Pull request merged**
