### PR TITLE
Age of user for Glare analysis

### PR DESCRIPTION
**Pull request by devngc**
Age of user added as an optional input. 

Sensitivity to glare differs between age groups as mentioned in [this ](https://www.radiance-online.org/community/workshops/2013-golden-co/wienold_glare_rad_ws2013.pdf) presentation (page 27-31). Since version 1.0 of evalglare, released in September 2012, there's already an option to account for the age of users in DGP calculation. I believe this input can help in case of the design of classroom space for school kids or spaces for senior citizen. Therefore, I added this input.

[sample](https://github.com/devngc/Work-in-Progress/tree/master/glareAnalysis)

Thank you!
-Devang

### CODE REVIEW

**Comment by chriswmackey** [comment]
@devngc ,
It looks like you have implemented it in a way that is respectful of the old methods but I unforuntately get a "Too many values to unpack" error when I run your sample file on my system:

valuestounpack

I'm not sure what exactly is causing this, but it looks like the result that I get out of evalGlare is just a statement that reads:
"age factor not supported any more "
image

If you address this, I can merge it in but I also realize this is not looking too hopeful.

In any case, the findings within the presentation that you posted are extremely interesting given that there's also new research demonstrating the importance of sun exposure during childhood eye development to mitigate the development of nearsightedness.  There are some real publications in the journal "Nature" that document this but this youtube video also gives a good sense of where the science currently stands:
https://www.youtube.com/watch?v=qwQzTKHIkb4&t=418s

Perhaps we shouldn't be subjecting younger people to such strict glare standards that adults require.

**Comment by devngc** [comment]
@chriswmackey ,
Thank you for the review. **I confirm that the age factor correction is indeed not supported anymore in evalglare**. I have been looking into this since this morning. Jan Wienold dropped the age factor since the evalglare relaese in 2015. I am using evalgare 1.11 from 2013, so it worked at my end. Unfortunately, we will not be able to account for age factor. Most likely, this PR will have to trashed, but I would still request you to give me some time. If I don't find a working solution in a couple of days, I will close this PR myself. Thank you for the video link. As a matter of the fact, I started looking into the effect of age on glare perception after recently I had a talk with a few fabulous teachers for a school project.

**Comment by sariths** [comment]
On that note, @mostaphaRoudsari @chriswmackey , you might want to update [installation instructions](https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Installation_Instructions.md)  to reflect the [new stable release for Radiance](https://github.com/NREL/Radiance/releases/tag/5.1.0).

**Comment by chriswmackey** [comment]
@devngc ,
You can take your time with the PR as there probably won't be any other updates to this component for a good while.  I'm interested in hearing the story behind why the ageFactor was dropped if you can track it down.

@sariths , I'll try to update that link shortly.

**Comment by devngc** [comment]
@chriswmackey @sariths ,
Please check page 06 of Jan Wienold's slide deck from Radiance Workshop 2016. The same can be found [here](https://www.radiance-online.org/community/workshops/2016-padua/presentations/211-Wienold-Evalgaare2.0.pdf). To find out more, I believe we should write to Jan Wienold. @sariths, I will wait for your link before I do that.
Thank you!

**Comment by mostaphaRoudsari** [comment]
FYI. I sent an email to Jan a couple of hours ago and asked for his input.

**Comment by wienold** [comment]
Hi guys,
Actually I had to remove the age factor since the evaluation of new data didn't show a statistical influence of the age on discomfort glare any more. We have tested subjects up to 70 years and the effect was not significant. I know we included the age factor at the Boulder workshop, based on a smaller dataset. At that time the statistical effect was already mentioned to be small. Maybe I should have waited to include until another study is confirming, but I usually try to include recent findings into the tool.  I also know that this "removal" is not nice for you, especially when you want to compare data, but I have to respect research results.  You can re-calculate in both directions your DGP-value by applying the equation on slide 29 of the boulder workshop, in case you want compare values from older to newer evaluations. 
I might have access to new user data next year and will evaluate this aspect again, but I don't expect a large influence and I will check again, if an effect of the age is statistically significant.
This is different for disability glare - for this type of glare it is well known that there is an influence, represented by the k factor in the CIE equation. However, this age influence of the disability equation is not implemented in the current version of evalglare, although the cie equation is calculated in evalglare. So far, only few people evaluate disability glare with evalglare. If your intention is the calculation of disability glare with evalglare, please let me know. I could activate the age function just for this equation and send you an updated version. Besides that, I will definitely put this on the list of things to be changed for the next version.

**Comment by sariths** [comment]
Hi @wienold , 
On this... 

> If your intention is the calculation of disability glare with evalglare, please let me know.

..the answer would be a resounding yes! Based on my experience over the last two years, the average Honeybee user is usually someone who is likely to be more proficient in modeling and grasshopper than Radiance. At present there are no stable ways of calculating disability glare within such an open source platform like Honeybee. Right now the options are primarily limited to evalglare or just considering raw luminance values from HDR images.
There are, however, a lot of people who are interested in being able to do such calculations (like parametric evaluation of building envelopes that predominantly glass-based). Actually, if there was someway to codify some of the concepts from your talk at the [Radiance workshop in London,](https://www.radiance-online.org/community/workshops/2014-london/presentations/day3/Brotas_SolarReflectedGlare.pdf) that will be great.

**Comment by wienold** [comment]
at the moment I'm really busy with other things, so I cannot include large changes into evalglare. 
However, the Stiles-Holladay disability equation is implemented in evalglare (see man page), just without the age correction. I just looked up the relevant cie-publication -the age correction for this equation is (1+(a/70)^4) for glare sources 1<angle<30° - you can easily modify the veiling luminance by this factor - this shouldn't be a problem. 
The general CIE-equation for disability glare(also for smaller angles) includes also eye-pigmentation information.  The equation is a bit different (but not complicated), but a proper documentation and some check routines are needed and will be therefore postponed to the next larger update.  
the workflow described at the radiance workshop is possible since many years - I used that for a report for a court trial in 2012. It was using evalglare only to calculate the angle between the glare source and the sun to see if this is smaller than 10°. The glare limit was an absolute in that case.

**Comment by sariths** [comment]
@mostaphaRoudsari We should probably have some outdoor glare examples on Hydra then. The last I checked, I only found this [one](http://hydrashare.github.io/hydra/viewer?owner=mostaphaRoudsari&fork=hydra_1&id=Glare_Analysis).

**Pull request closed without merging**
