### PR TITLE
Added Comfort Ranges

### PR DESCRIPTION
**Pull request by devngc**
screenshot

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@devngc thank you for sending this PR. Looks great! The code looks very clean and will be quite useful. A couple of comments and a wish.

1. Output naming should be camelCase (e.g. comfortRange)
2. You need to send .py and .ghuser files for the new component. Currently it's only the .py file.

and the wish is to add this to the text that is printed on top of the  image. It's currently [happening only for dgp value](https://github.com/devngc/Honeybee/blob/cda7cab52d254523e1ebabbcf72df422495c39d2/src/Honeybee_Glare%20Analysis.py#L259-L262).

If you can address items 1 and 2 I can merge it in.

**Comment by devngc** [comment]
Hi Mostapha,

Adding Comfort range result to the image sounds like a great. I didn't
think about it. Thanks for the same. Will work on it and revert back.

Thanks,
*Devang*

**Comment by devngc** [comment]
Hi Mostapha,

I have addressed task 1, 2, and the wish as well. Please let me know if there's anything you want me to do regarding this pull request.

Thanks,
Devang

**Comment by mostaphaRoudsari** [comment]
@devngc thanks! I'm merging this in. I will make a minor change in the wording so it shows as Glare Range first and then the glare number.

**Pull request merged**
