### PR TITLE
tolerance of Infiltration Ratio

### PR DESCRIPTION
**Pull request by mauricio-aguilar**
changed tolerance to be able to convert critically low infiltration
values

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
Thanks @mauricio-aguilar!
cc: @ayezioro

**Comment by ayezioro** [comment]
Thanks @mauricio-aguilar 
The reason of the limitation, when we talk about airfow/volume is/was not allowing to low values leading to "unreal" values or values not allowing proper minimal ventilation as for health reasons. 0.2 ACH is very low, and i'm not sure it is allowed for the reason i mentioned.
I neeed to see how to overcome both requirements: health and @50PA vs ambient conversion.
-A.

**Comment by mauricio-aguilar** [comment]
Abraham,

You're absolutely right, health is a concern. In my scenario I was
considering or implying the use of an MVHR which gives you the necessary
ventilation but reduces air infiltration losses to a minimum, and therefore
allows for such low levels of air tightness.
But if we change the tolerance other people may mis-use this feature.
I could maybe add a component warning? something like "critically low
ventilation values detected, additional ventilation is suggested for health
compliance"
regards,
M

**Comment by mostaphaRoudsari** [comment]
A proper warning sounds like a great idea to me!

**Comment by ayezioro** [comment]
I've just sent a pull request for the new version.
I limited the input to 0.2 ach always measured at ambient conditions. Added a new boolean input @50PA, which will make the proper conversion.
More checkings were added for inputs.
Please do check the pull request is fine ...
-A.

**Pull request merged**
