### PR TITLE
LookUpFolder E+

### PR DESCRIPTION
**Pull request by ayezioro**
Set the studyType as compulsory input. Comment.

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
Hi Abraham. Did you sync before sending the pull request? There is conflict which I guess is happening because of the changes that Chris has made to the component recently. It should be the date line: https://github.com/mostaphaRoudsari/Honeybee/blame/master/src/Honeybee_Lookup%20EnergyPlus%20Folder.py

**Comment by ayezioro** [comment]
Hi Mostapha,
I forgot to change the date in the component.
I did it now. Hope it is fine. is it?
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

There are still conflicts because I had updated your component to reflect the Ladybug Graphic Standards with this commit:
https://github.com/mostaphaRoudsari/Honeybee/commit/a8370cac51fff5042c4661b9bfdd558d4d25761c
All that I did was move the checks out of the main function and called a few other LB_LB functions for input checking (functions that all LB+HB components now call since the last stable release).  This is consistent with the new template that new components should use:
https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Ladybug_Component_Template.py

Your current pull request is undoing this change that I made to conform with the standards and so it cannot automatically be merged in.

Can you sync with the github and make your changes to a component that you pull down from the toolbar as opposed to starting from your old GH definitions?  This will ensure no sync conflicts.

-Chris

**Comment by chriswmackey** [comment]
@ayezioro ,
Actually, I am seeing that your new commit is conforming to the graphic standards and so I am not sure why the merge conflict is happening.  Did you send a pull request to update your fork of the code with the master branch before you committed your new component to your fork?

If not, I think this might be the reason why.  If you revert your change to your fork and send a pull request to sync your fork with the master, commit the changed component to your fork, and then send us another pull request here, that should fix the issue.

-Chris

**Comment by ayezioro** [comment]
Hi Chris,
What i did (and did it again just now) is selecting the change on the left side of the git application. Then i commit it. Then sync it and then pull request. Right now the application is not allowing the pull but just the sync.
I think i'm messing this too much ...
-A.

**Comment by mostaphaRoudsari** [comment]
@ayezioro @chriswmackey I resolved the conflicts and merge this. Abraham, the conflict was made in a previous commit. Your fork was behind the master branch when you commit the changes.

**Comment by ayezioro** [comment]
Thanks Mostapha,
One day i'll get this ... in the meantime bare with me :-)
-A.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Thanks for taking care of this.
-Chris

**Comment by ayezioro** [comment]
Hi,
Do you know why this component is not included in the github updated files?
Just wonder ...
Also the Daysim LookUpFolder isn't there.
Thanks,
-A.

**Pull request merged**
