### PR TITLE
IES Components for Honeybee

### PR DESCRIPTION
**Pull request by sariths**
Details to follow..

### CODE REVIEW

**Comment by sariths** [comment]
Attached are some images from Image Based Simulation.All the images with dark skies and lighting are using the IES components while the ones with daylight already are possible with Honeybee

1-3-2016 9-27-32 pm
1-3-2016 9-28-36 pm
1-3-2016 9-30-21 pm
1-3-2016 9-33-27 pm
1-3-2016 9-34-45 pm
1-3-2016 10-13-17 pm

unnamed_img_perspective fc
1-3-2016 9-22-14 pm

**Comment by mostaphaRoudsari** [comment]
@sariths this is freaking awesome. Do you have any example files that you also want to share?

**Comment by sariths** [comment]
@mostaphaRoudsari Right now I have loads of garbage files pretending to be example files. The screenshot you see is crazy and confusing. I will send you a clean example tomorrow.

1-3-2016 10-41-42 pm
I was thinking of creating some short clips explaining what is going on. And also create some simple examples on Hydra. Can we skype sometime within this week ?

**Comment by mostaphaRoudsari** [comment]
@sariths great! Hydra is the right place to share the example files. Sure we can talk but let's decide about the exact time later this week.

**Comment by chriswmackey** [comment]
Oh, man!  This is really freaking cool!
I'm sending these images to the visualization team in my office right now.
Very excited for example files.

**Pull request merged**
