### PR TITLE
Addad Summary Report output

### PR DESCRIPTION
**Pull request by MingboPeng**
have energyplus generate Building Performance Summary report by default

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
looks good! thanks.

**Comment by chriswmackey** [comment]
This is great @MingboPeng . Thank you!

**Comment by chriswmackey** [comment]
@MingboPeng ,
I realized that this html output is always generated by OpenStudio and it's always in metric (so, effectively, this option does not work for the component that we are recommending that everyone use).  I just decided to make things consistent between OpenStudio and the old E+ component and have both output the html automatically with each run:
https://github.com/mostaphaRoudsari/honeybee/commit/e7e75ee765b8d1ede64b73fc2fdd562b885b79e5
Let me know if this still gives you what you need and, if not, feel free to send another pull request that works for both the E+ and OpenStudio components and I'll merge it in.

**Comment by MingboPeng** [comment]
@chriswmackey  Thanks for fixing it, I will try it.

**Pull request merged**
