### PR TITLE
added HVACSystem input

### PR DESCRIPTION
**Pull request by MingboPeng**

### CODE REVIEW

**Comment by chriswmackey** [comment]
@MingboPeng ,

As I understand it, this input is supposed to take your C# objects that represent HVAC systems, correct?

Am I mistaken that this PR does not add in the full functionality of the HVAC systems?  Or is everything is wrapped up in an elegantly simple call to an API here?
https://github.com/mostaphaRoudsari/honeybee/pull/713/files#diff-ee5b71091392011f4b3dac1b58cfdee7R5592

**Comment by MingboPeng** [comment]
@chriswmackey  you are correct, all functions is wrapped in `HVACSystem.SaveHVAC(fname)`

**Comment by chriswmackey** [comment]
@MingboPeng ,

Wow, that is very elegantly simple!  Good job on API design!

I will merge this in once I finish updating some files that I wanted to share publicly, which I want to be synced to the last stable release (This should be later today or tomorrow).

Are you planning to coordinate this with a release of the ironbug components to Food4Rhino?  I just wanted to get your thoughts on the timeline.

**Comment by chriswmackey** [comment]
We are all good to go!  Now we can really support some people testing out the ironbug components with an up-to-date OpenStudio component.

**Comment by MingboPeng** [comment]
@chriswmackey  Cool, thanks. for the Food4Rhino package, are you going to zip the Ironbug files together with Ladybug and Honeybee? if yes, please download this https://github.com/MingboPeng/Ironbug/releases/download/0.1.1/Ironbug.zip
and unzip it. I also included an installation gh file in it. 

Users need to do an extra step to install it.
Please let me know if this works.

Thanks,
Mingbo

**Comment by chriswmackey** [comment]
@MingboPeng ,

Let me get @mostaphaRoudsari 's thoughts on it when I get the chance.  My initial thought about releasing it in the same package as the legacy plugins is that it would make the plugin much heavier and there are already close to 400 components in there.  Other options would be to release it as another standalone release under Ladybug Tools (similar to how the plus plugins are released alongside the legacy) or as a separate plugin on Food4Rhino (somewhat like Clarke's crow, which has dependencies on Honeybee).  Let's take our time and figure out the best means and I think we will probably want to leave it as install-able from github for a while just to make sure that we've had enough people test it before official release.

**Comment by mostaphaRoudsari** [comment]
Hi @MingboPeng,

I think we should follow a plugin pattern here and release it as a separate page on Food4Rhino. This is in-line with our recent conversations for breaking down the libraries and following a core + plugins pattern. [Think of flask and all its extensions](http://flask.pocoo.org/docs/1.0/extensions/).

It will also make the whole process of development, release and maintenance easier.

Somewhat related and very good read: https://12factor.net/

**Comment by mostaphaRoudsari** [comment]
PS: after we get the icon fixed we should also consider adding Ironbug to Ladybug Tools page! We should discuss how to include it on the page so more people know about it.

**Pull request merged**
