### PR TITLE
Added update logs window

### PR DESCRIPTION
**Pull request by MingboPeng**
HoneybeeCSharp: create a window reads updatelogs.md

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@MingboPeng thank you for sending the PR. What does honeybeeCsharp.exe do?

**Comment by MingboPeng** [comment]
At this time, HoneybeeCSharp.exe is a Windows window that reads updateLogs.md, and presents the content to user after every update. HoneybeeCSharp's code is under my GitHub account, and I'm trying do develop it as a standalone tool that receives the commands from honeybee in grasshopper, and runs outside of grasshopper (for example: HoneybeeCSharp launches and runs energy+ inside of it after it gets a notice from HB-runEP, and returns a notice to HB-runEP when it's done), which will release grasshopper and rhino while doing simulation. Users might have a better experience from an unfrozen grasshopper.

**Comment by chriswmackey** [comment]
@MingboPeng ,

Great job!  I definitely understand the desire to run applications like E+ and Radiance independently from Grasshopper but the update window might be a bit more information than most users need.  I am going to merge your work in now and check it out but please don't take it as a sign that your work is not appreciated if I edit it.  Whatever the case, we can keep the C# file for now in case you want to add the ability to run E+ without freezing GH.

Also, so that you are aware of the direction that things are moving in: the next version of [Honeybee](https://github.com/ladybug-analysis-tools/honeybee) that @mostaphaRoudsari and @sariths have been working on will be mostly independent of Grasshopper and will require the installation of Python 2.7. As such, there will be no need to have a C# file to run E+ and Radiance independently of Grasshopper (we will do it all with Python!).

We are going to have one more release of the current Honeybee version so this C# file should be useful for at least another 6 months.

Thanks again for contributing it.
-Chris

**Comment by chriswmackey** [comment]
@MingboPeng ,

I tried out the components and realized that nothing really changed from the typical user's perspective.  This is because there is no code that automatically downloads the update log from the github.  If you would like to implement such code, I would be in support of it under the sole condition that the displaying this log is optional for the user.  I might suggest adding a boolean option to the "Update Honeybee" component called "displayUpdateLog", which downloads the log and displays the popup window.

Keep us posted if you plan to implement this,
-Chris

**Comment by MingboPeng** [comment]
@chriswmackey Thanks for telling the direction that Honeybee are heading. I remember that Mostapha  told me he was making APIs for both GH and dynamo. But running python out of GH is a really good idea, and that is something what I want to do now. As we discussed after MEBD's final, the GH itself is limiting the performance of Honeybee, moving the heavy work part away from GH and Rhino might increase the computing speed.

Since Mostapha is working on this as well, I think I can move to the other aspects. I am also working on Ladybee_library community that allows users to share their customer settings, colors, materials, schedules, etc.

**Comment by chriswmackey** [comment]
@MingboPeng ,
I agree that ironpython is currently limiting a lot of our capabilities and I'm excited t be developing a brand new API with the full Python 2.7.
I'm interested in seeing this Ladybee library once it is together.

**Pull request merged**
