### PR TITLE
Correction to gbXML to Honeybee component for OS 2.7 compatiblity and correcting material/construction loading into corresponding HB dictionaries

### PR DESCRIPTION
**Pull request by saeranv**
There are two modifications here, one to the way in which the OpenStudio API is used to load the OSM model from a gbxml file, and secondly to the way materials/constructions are loaded into Honeybee from the gbxml method. 

For the first one: I've recently been working with a recent build of OpenStudio (2.7+) in order to get access to a working version of the gbXML translator (see details here https://github.com/NREL/OpenStudio/issues/3296). The previous HB method wasn't working to load the gbxml model from the translator, and with some coaching from the OS developers, I changed the file import method. This is for the latest OpenStudio build only, and I haven't tested it on previous releases, so it might make sense to reject this part of the PR for now. I just wanted to make sure it was documented somewhere here in case it was needed when the upgrade to OpenStudio 2.7+ eventually occurs. 

Secondly, the materials/constructions from my gbXML were not being found by the Honeybee Decompose from EPConstruciton component. It looks like it's because of this code in that component: 

https://github.com/mostaphaRoudsari/honeybee/blob/4e67a49996da8dba818430a3516474d83105249a/src/Honeybee_Decompose%20EP%20Construction.py#L76-L83

which is looking for an uppercase version of the gbxml-added construction/material names. 

So I changed the method in which the gbxml materials/construction names are added to the Honeybee material/constructions library as keys, which seems to have fixed the problem.

I've never really worked with this part of the HB code, so I'm not sure if this is neccessarily the correct way of dealing with these bugs! However with this I managed to import all the materials/constructions from a gbxml file into Honeybee, which is a crucial workflow process we need at KT. 

-S

### CODE REVIEW

**Comment by chriswmackey** [comment]
@saeranv ,
Thank you for doing this and I know that there were so many changes with OpenStudio 2.7 that broke a lot of existing workflows.  We should definitely get these fixes in before the next stable release of Honeybee legacy.

Your changes makes sense and, to be honest, the legacy version code here really doesn't have too many rules to it (it's not like the core libraries where we need all of the code to be clean).  As long as the code works, I will merge it but, in order to do so, we need to have it working in both current AND older versions of OpenStudio.  I would parse the path to openstudio like I do here:
https://github.com/mostaphaRoudsari/honeybee/blob/master/src/Honeybee_Export%20To%20OpenStudio.py#L111-L120
Then, you can use the version to decide which code to use depending on which version of OpenStudio is loaded.

Thank again!

**Comment by chriswmackey** [comment]
@saeranv ,
Also, feel free to ask if I can do it.  I'm happy to take your code and make it work for both versions of OpenStudio if you are busy.

**Comment by saeranv** [comment]
@chriswmackey 

Thanks for offering to do it. I'm on vacation right now, so if you can do it that would be great. If not I can get to it next week. 

-S

**Comment by chriswmackey** [comment]
Ok, I am on it!

**Comment by chriswmackey** [comment]
I have gotten it working for both past and present version of OpenStudio with this commit:
https://github.com/mostaphaRoudsari/honeybee/commit/7a1803b1bf1931f633991eff2fee8e6af3d5fa18

@saeranv , adding constructions to the library with .upper() created a lot of bugs so I have left it out. and all constructions were imported and simulated correctly when I did so.  Let me know if that is not the case for you.

I am closing out this issue but feel free to repoen it if you find any issues with the commit I pushed.

**Comment by saeranv** [comment]
Thanks it looks like it should work! Good call on updating the OpenStudio to gbxml method as well, I totally forgot about that.

**Pull request closed without merging**
