### PR TITLE
Merge Honeybee Earthtube, Honeybee PV generators updated Run E+ and select by type into master

### PR DESCRIPTION
**Pull request by antonszilasi**
Gents,

After 2 hard weeks of working on these I'm happy to say that these are my first real components so lets get them out there and beta tested! I will put some short tutorials about them on youtube tomorrow for beta testers.

I'll now go back and polish the ground temp component over the next 2 days after that I'll look at solar hot water and afterwards look at water usage in zones.

Cheers!

### CODE REVIEW

**Comment by antonszilasi** [comment]
also forgot to add since Im an engineer im no artist could you guys kindly come up with some icons for the PV generator and Earthtube component?

**Comment by chriswmackey** [comment]
@antonszilasi ,

For some reason, we cannot automatically merge the pull request.  it looks like you were not able to get your Honeybee up to date before making the changes for your new components.  Can you try merging a pull request to Moastapha's branch first?
I emailed you the link to the icon file.
-Chirs

**Comment by mostaphaRoudsari** [comment]
@chriswmackey did you also designed the icons? I think @antonszilasi needs some help with designing the icons. If you still need help on that I can give it a first try and you can customize it as needed. @stgeorges how does your icon for PV component looks like?

**Comment by stgeorges** [comment]
It's a PV module with purple cells and a power sign on it.
It was suppose to have white background (resembling the color or the PV crystalline silicon back polymer surface), but it didn't look good with white one, so I decided to take the black background instead:

pvsurface_icon

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

The icons in the email that you sent look good.  I didn't make any icons of my own but I shared the .ai file with Anton in case he wants to make icons of his own in the future.  I am also happy to help with future icon-making.

-Chris

**Comment by mostaphaRoudsari** [comment]
I think we should have similar icons for PV components and then Add some notes to make them different. @stgeorges can you make this work? This is what I suggested for @antonszilasi's component. Just for your information. You don't have to use it.
pv_generator

**Comment by stgeorges** [comment]
@mostaphaRoudsari , @antonszilasi,
It looks nice.
Still I would be very grateful if I could keep the present one. I somehow prefer it.
I had some other variations, but they did not look that good when they were put on a component:
pvmodules2   pvmodules6   
pvmodules8   pvmodules7   pvmodules9

**Comment by mostaphaRoudsari** [comment]
Hi @stgeorges, I don't think you should change yours but is there a way that you can generate a similar icon for @antonszilasi 's development so we can keep it consistent?

**Comment by antonszilasi** [comment]
Hi everyone, I using this icon for PV, @stgeorges has been kind enough to design the icons for the other Honeybee generation components!
pv_generator

**Comment by stgeorges** [comment]
Hi @antonszilasi, @mostaphaRoudsari, @chriswmackey 
Just so that the others may give opinion on this, I think that due to the fact that Mostapha approved my upper icon for PV component (
pvmodules11
) it may be the best to use the same one for Anton's Honeybee component, but with a blue color instead:
pv
For my set of PV components I would always use purple color, while Anton can use blue. In this way a clear distinction between Ladybug and Honeybee PV components will be present.

**Pull request closed without merging**
